BugSplat-Git/symbol-upload

- lib/bugsplat-api-client.ts
We were returning set-cookie value to delete a legacy xsrf-cookie on another domain which was resulting in 2 xsrf-cookie regex matches. Now that we've removed the legacy cookie we match on the first instance os xsrf-cookie.
Fixes #14
> Fixes xsrf-token parsing

- bin/command-line-definitions.ts
- bin/index.ts
- index.ts
- package-lock.json
- package.json
Uses [command-line-usage](https://www.npmjs.com/package/command-line-usage) and [command-line-args](https://www.npmjs.com/package/command-line-args) to standardize the parsing of our command-line arguments and print a standardized help message.
```
PS /Users/bobby/Desktop/bugsplat/symbol-upload> node ./dist/bin/index.js -h
@bugsplat/symbol-upload
symbol-upload contains a command line utility and set of libraries to help    
you upload symbols to BugSplat.                                               
Usage
-h, --help                          Print this usage guide.                                                       
-b, --database string               Your BugSplat database name.                                                  
-a, --application string            The name of your …
```
> Standardize Command-Line Parsing

- .gitignore
- .vscode/launch.json
- README.md
- bin/command-line-definitions.ts
- bin/index.ts
- package-lock.json
- package.json
Gets application, and version from package.json if it exists in the current working directory. Gets database from SYMBOL_UPLOAD_DATABASE env variable.
Fixes #21
> feature: Get application, version, and database automatically

- README.md
- bin/index.ts
- index.ts
- package-lock.json
- package.json
- Parse debug ids if uploaded file has a `.sym` extension. 
- Update to @bugsplat/js-api-client v2
- Updates README to match new conventions
Fixes #33 Fixes #35 Fixes #36
BREAKING CHANGE: now exports VersionsApiClient instead of SymbolsApiClient
> feat!: support dbg id in sym files

- README.md
Package exports OAuthClientCredentialsClient not OAuth2ClientCredentialsClient.
> docs: fix readme samples

- .gitignore
- package-lock.json
- package.json
Adds pkg for building native binaries for Nineva.
Breaking Change: requires node 18 or later.
> chore!: add support for binary build

- .vscode/launch.json
- bin/command-line-definitions.ts
- bin/index.ts
- bin/worker.ts
- package-lock.json
- package.json
- spec/support/jasmine.json
- spec/worker.spec.ts
> feat: support parallel uploads

- bin/index.ts
When we package up our node app, the way you find the current working directory is different:
| value                         | with `node`     | packaged                 | comments                       |
| ----------------------------- | --------------- | ------------------------ | ------------------------------ |
| \_\_filename                  | /project/app.js | /snapshot/project/app.js |
| \_\_dirname                   | /project        | /snapshot/project        |
| process.cwd()                 | /project        | /deploy                  | suppose the app is called ...  |
| process.execPath              | /usr/bin/nodejs | /deploy/app-x64          | `app-x64` and run in `/deploy` |
| process.argv[0]               | /usr/bin/nodejs | /deploy/app-x64          |
| process.argv[1] …
> fix: use correct temp dir

- .gitignore
- bin/index.ts
- bin/util.ts
- bin/zip.ts
- package-lock.json
- package.json
- spec/zip.spec.ts
Replace adm-zip with archiver and use write stream to write temporary zip file as a workaround to node's 2GB buffer limit.
> fix: support files larger than 2GB

- action.yaml
> chore: remove setup-node step from action

- bin/index.ts
- bin/symbol-file-info.ts
- bin/tmp.ts
- bin/worker.ts
- package-lock.json
- package.json
- spec/tmp.spec.ts
- spec/worker.spec.ts
We know that the Windows file system can be super sus and hang on to files. This change does the following:
* Ensures that we release the handle on tmpZipFile when there's an error
* Retries deleting the tmp directory with an exponential backoff
Fixes #60
> fix: error ENOTEMPTY deleting tmp

- .vscode/launch.json
- bin/gzip.ts
- bin/index.ts
- bin/symbol-file-info.ts
- bin/worker.ts
- bin/zip.ts
- index.ts
- package-lock.json
- package.json
- spec/gzip.spec.ts
- spec/worker.spec.ts
Upload `.pdb`, `.dll`, and `.exe` files with guids to our new s3 symsrv location.
I also fixed an issue where a stream was getting destroyed by garbage collection instead of explicitly destroyed which may fix #61 
Resolves #65
> feat: s3 symsrv support

- spec/worker.spec.ts
- src/worker.ts
Now that we're not using the bsv1 protocol we need to instruct the backend that this is a zip file.
Fixes #82
> fix: source map uploads

- README.md
Make it clear the GitHub action uploads symbols to BugSplat
> chore: add GitHub action blurb

- .github/workflows/pr.yaml
- README.md
- action.yaml
- package.json
We had initially taken out the setup-node step in fear that it might interfere with the setup-node step of the calling action. This doesn't appear to be an issue after all.
Additionally, by including a setup-node step, the calling action doesn't have to worry about calling setup-node, which is a better solution for actions that otherwise wouldn't use node.
Finally, for actions already using node, we expose a `node-version` input so that the calling action can dictate which version of node symbol-upload uses.
Fixes #97
> fix: make action standalone

- src/worker.ts
See #98.
Not sure about other use-cases, but on Linux when trying to upload a .sym file, symbol-upload tries to write into a temporary subdirectory which doesn't exist and therefore the upload fails.
This is a straightforward fix.
Fixes #98.
Feel free to implement this in another way if this does not capture the intent. If any unit tests/documentation if needed I'd rather leave that up to you.
> fix: temporary directory for .gz files

- package-lock.json
- package.json
- spec/dsym.spec.ts
- spec/elf.spec.ts
- src/elf.ts
Elfy updated to v1.0.1 which includes fix for parsing ELF strings table in correct order. Adds offset to the `.note.gnu.build-id` bytes we use for the UUID since that's how readelf seems to work.
> fix: elf guids

- .github/workflows/pkg.yaml
- .github/workflows/pr.yaml
- .vscode/launch.json
- bin/command-line-definitions.ts
- bin/index.ts
- package-lock.json
- package.json
- src/upload.ts
- src/worker.ts
Adds dump_syms functionality via the Mozilla dump_syms crate. When invoked with the `-m` flag, any binaries the glob finds will be converted to `.sym` files and uploaded.
Depends on https://github.com/BugSplat-Git/node-dump-syms/pull/8
BREAKING CHANGE: removes glob support from `uploadSymbolFiles`
> feat: add dump_syms

- bin/index.ts
- package-lock.json
- package.json
- spec/sym.spec.ts
- src/sym.ts
The backend seems to be looking for myQtCrasher.sym instead of myQtCrasher.pdb.sym etc.
> fix: remove file extensions from sym file

- spec/sym.spec.ts
- src/sym.ts
Apparently Windows is the only platform where the minidump-stackwalk backend looks for modules containing extensions.
> fix: include extension in windows module name

- bin/index.ts
- spec/sym.spec.ts
- src/sym.ts
Work around weirdness in rust-minidump-stackwalker symbol file lookup requests.
###
> fix: sym file lookup

- bin/index.ts
Allows user to specify BugSplat database in package.json. This is really useful for electron as it gives us an accessible spot to share the value between the native, main, and renderer handlers.
> fix: support database in package.json

- .vscode/launch.json
- src/upload.ts
Extension .prx was requested by Warhorse and I noticed that .sprx was also searched for by the debugger. I believe .prx is the extension for PlayStation Plugins and .sprx is a signed version of .prx (similar to .elf and .self)
Before:
After:
> feat: support prx and sprx

- bin/index.ts
- spec/dsym.spec.ts
- spec/worker.spec.ts
- src/dsym.ts
- src/info.ts
- src/upload.ts
- src/worker.ts
There's some weird logic in here we use so that files with the same name but in different folders don't overwrite one another in the temp directory. To avoid this, we prefix the file name with the path to the file. Since 2 files with the same name can't be in the same folder this works because the prefix is always different, but it also gives us some idea where the symbol came from.
Fixes #108
BREAKING CHANGE: changes signature of public function uploadSymbolFiles
> fix!: enoent searching for symbol files

- .github/workflows/pr.yaml
- action.yaml
Use pwsh as runner, according to ChatGPT it's available on Windows, macOS, and Linux GitHub Actions runners. Also updated test action to run on windows-latest, ubuntu-latest, and macos-latest to verify.
> fix: add windows compatibility

- package-lock.json
- package.json
- src/dsym.ts
- src/worker.ts
The `:` was gunking things up. Adds filenamify which removes non-allowed Windows path characters.
Fixes #113
> fix: no such file or directory, mkdir 'C:\BuildAgent\****\tmp\C:'

- src/worker.ts
Test runs so fast the time ends up being 0 causing prettyBytes to fail because anything divided by 0 is NaN.
> chore: fix unit tests

- src/upload.ts
- src/worker.ts
For large file lists we're firing off like 40000 promises at once. Node's async I/O is supposed to handle this, but it seems like at these numbers everything falls apart. We open hundreds of file descriptors, and requests start to fail because we're absolutely hammering the backend and perhaps even overwhelming the sending machine. This change awaits each upload requests so there's at most 16 going simultaneously instead of an indeterminate amount.
> fix: don't fire uploads promises all at once

- bin/index.ts
- package-lock.json
- package.json
- spec/worker.spec.ts
- src/compression.js
- src/upload.ts
- src/worker.ts
1. Don't fire an unlimited number of promises, this seems to crater node when uploading 1000s of files
2. When we retry, we need to recreate the stream if we're going to destroy it
3. Update bugsplat-js-api-client so that we close the teed stream after we're done reading, this alleviates backpressure which was causing us to leak memory
4. Update bugsplat-js-api-client so that we close the upload read stream when the upload fails
5. Use proper tmpSubDir to prevent file overwrites
> fix: readable stream locked

- bin/index.ts
- sea/windows.ps1
Create tmp dir before asking node-dump-syms to write there.
Fixes #127
> fix: symbol-upload-linux fails if tmp dir doesn't exist

- package-lock.json
- package.json
Didn't realize we broke Second Life by going to node 22. Doing a major version rev to reflect the breaking change.
Now customers get a warning:
```bash
bobby@Mr-Presidents-MacBook-Pro symbol-upload % npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bugsplat/symbol-upload@9.2.3',
npm WARN EBADENGINE   required: { node: '>=22' },
npm WARN EBADENGINE   current: { node: 'v20.11.1', npm: '10.2.4' }
npm WARN EBADENGINE }
```
> chore: require node 22

- action.yaml
The dumpSyms switch was not included in the exposed parameters/inputs fto the github action. 
This PR enables it. 
--dumpSyms is a simple switch, so we need more logic than the other string params. 
Also, pwsh is weird, so we check dumpSyms value to be explicitly set to the 'true' value
when using dumpSyms you may need to install `node-dump-syms`
```
- name: Install node-dump-syms
if: runner.os == 'Linux'
run: npm install -g @bugsplat/node-dump-syms     
```
Note: this has been tested on Windows only as this fix has moved me forward to needing to resolve other issues in my pipeline before I can properly test on macOS and Linux as well. 
Fixes #135
> fix: update action.yaml for dumpSyms support

- src/elf.ts
- src/upload.ts
NSS appears to just be a typical ELF file. There is some weirdness with the build IDs... here's what we get in the crash report for `module_id`:
```
1e0b323c7d1a24dd142f3d3f94ac642600000000000000000000000000000000
```
but symbol-upload gets
```
1e0b323c7d1a24dd142f3d3f94ac6426
```
We've seen length of 32 and length of 40. For now we're just 0 padding to reach a length of 64 because a fix that used big ints in elfy would be a ton of work.
> feat: allow nss uploads for Nintendo

- .github/workflows/pr.yaml
- README.md
- action.yaml
- package-lock.json
- package.json
The node-dump-syms install script incorrectly tried to invoke node-pre-gyp and would fail if the package wasn't installed globally. This change updates to a version of node-pre-gyp that invokes @mapbox/node-pre-gyp with npx, which will fetch that dependency if it doesn't exist. Also a few minor readme updates and build action updates.
> fix: node-dump-syms install step

- bin/command-line-definitions.ts
Changed singled quotes to double quotes in the files usage example.
Fixes #143
> fix: update command line help

- package-lock.json
- package.json
- src/worker.ts
Use last modified time of file being uploaded instead of temp file.
> fix: symbol last modified time

- src/worker.ts
This change simplifies the way we do temp files so we don't end up with weird characters in the path.
I think the original approach was supposed to handle same file names in different directories and also give us some breadcrumbs for debugging. However since we haven't needed it thus far the approach was most likely YAGNI.
Fixes #148
> fix: exFAT error

- .github/workflows/test.yaml
- spec/support/liba.dylib.sym
- spec/sym.spec.ts
- src/sym.ts
The minidump-stackwalk executable from rust-minidump looks for liba.dylib/GUID/liba.dylib.sym and we were storing it as liba/GUID/liba.dylib.sym.
> fix: module name for dylib sym files

- bin/index.ts
- src/sym.ts
We were removing all of the extensions from file names when using the -m flag. This doesn't appear to be correct. There seem to be a few extensions that aren't truncated (.pdb and .so.x). Additionally on macos the .dylib extension appears to be left alone and module.dylib.dSYM and application.app.dSYM are truncated to module.dylib.sym and application.sym respectively.
> fix: sym file names

- bin/index.ts
- spec/sym.spec.ts
- src/sym.ts
The logic used to determine the module and sym file names used by Crashpad is bananas.
* `.pdb` exists in the module portion of the path but not the sym file name eg, `thing.pdb/GUID/thing.sym`
* `.so.*` exists in both the module portion and the sym file name eg, `thing.so.6/GUID/thing.so.6.sym`
* `.dSYM` always gets removed, and `.dylib.dSYM` gets trimmed to `thing.dylib/GUID/thing.dylib.sym` but `.app.dSYM` gets trimmed to `thing/GUID/thing.sym`
* `.debug` always gets removed, and `.so.2.debug` gets trimmed to `thing.so.2/GUID/thing.so.2.sym`
Fixes #160
> fix: dump_syms fails due to incorrect path handling
