index.ts

Make -files an optional argument

---

src/symbols.ts

Should throw when getPresignedUrls returns Status "Failed"

---

.vscode/launch.json
index.ts

Support Environment Variable for Username and Password

---

tsconfig.json

Generate Type Declarations

---

tsconfig.json

Clean up tsconfig.json

---

package-lock.json
package.json
tsconfig.json

Fixes npm link is broken #17

---

package-lock.json
package.json

Updates broken @bugsplat/js-api-client

---

README.md
bin/index.ts

Updates README.md

---

bin/index.ts
package-lock.json
package.json

fix: support dbg ids for sym files

---

bin/index.ts

fix: upload support for .app and .dSYM files

---

bin/command-line-definitions.ts
bin/index.ts
bin/worker.ts
package.json
spec/worker.spec.ts

fix: serialize zips to disk before uploading

---

bin/index.ts

Don't try and create nested tmp dirs

fix: support files in nested directories

---

action.yaml

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #51
- [n/a] Unit tests pass with no errors or warnings
- [n/a] Documentation updated (if applicable)

chore: reusable action

---

README.md

chore: add action snippet to readme

---

bin/worker.ts
spec/worker.spec.ts

fix: retry failed symbol uploads

---

bin/index.ts

fix: unknown option messages too verbose

---

bin/worker.ts

fix: don't double zip files

---

bin/sym.ts
spec/support/spaces.sym
spec/sym.spec.ts

fix: module name with spaces in sym file

---

bin/index.ts

Uploads sym files to new s3 symsrv.

feat: upload sym files to symsrv

---

.vscode/launch.json
bin/index.ts
package-lock.json
package.json
spec/dsym.spec.ts
src/dsym.ts
src/info.ts
src/upload.ts
src/worker.ts

Support for exploding fat macho files and uploading them to BugSplat's symsrv compatible s3 bucket.

feat: dsym guids

---

bin/command-line-definitions.ts
package.json

fix: global install can't find package.json

---

package-lock.json
package.json
src/worker.ts

Depends on https://github.com/BugSplat-Git/bugsplat-js-api-client/pull/123

fix: don't retry auth errors

---

package-lock.json
package.json
src/upload.ts
src/worker.ts

```
Worker 1 uploading 1 symbol files...
Worker 2 uploading 1 symbol files...
Worker 3 uploading 1 symbol files...
Worker 4 uploading 1 symbol files...
Worker 5 uploading 1 symbol files...
Worker 2 uploading corrupt.exe.zip...
Worker 5 uploading bssndrpt.exe...
Worker 1 uploading portable.pdb.zip...
Worker 4 uploading bugsplat.dll...
Worker 3 uploading bugsplat.pdb...
Worker 2 uploaded corrupt.exe.zip! (149 B @ 116 B/sec)
Worker 1 uploaded portable.pdb.zip! (21.5 kB @ 15.2 kB/sec)
Worker 5 uploaded bssndrpt.exe! (185 kB @ 102 kB/sec)
Worker 4 uploaded bugsplat.dll! (223 kB @ 116 kB/sec)
Worker 3 uploaded bugsplat.pdb! (2.6 MB @ 928 kB/sec)
Uploaded 5 symbols totaling 3.03 MB @ 995 kB/sec
```

feat: add stats to uploads

---

bin/index.ts

chore: fix build

---

.github/dependabot.yml
package-lock.json

Fix npm audit vulnerabilities. Introduce monthly dependabot check.

fix: npm audit

---

.github/workflows/sea.yaml

Add build for intel macs.
Fixes #150

fix: macOS x86_64 binary

---

.github/workflows/sea.yaml

I'm a dork and didn't check Claude's work.

fix: intel build

---

README.md
bin/command-line-definitions.ts
bin/index.ts
index.ts
package-lock.json
package.json
sea-config.json
sea/linux.sh
sea/macos.sh
sea/windows.ps1
spec/compression.spec.ts
spec/fs.spec.ts
src/compat.ts
src/compression.js
src/compression.mjs
src/preload.ts
tsconfig.cjs.json
tsconfig.esm.json

fix: options `-h` and `--help` return exit code 1
